// Generated by Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import NetService;
@import UIKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("CulturalCloudBase")

SWIFT_CLASS("_TtC17CulturalCloudBase10BaseConfig")
@interface BaseConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSMutableURLRequest;
@class NSMutableDictionary;
@class ResponseModel;

SWIFT_CLASS("_TtC17CulturalCloudBase14BaseNetService")
@interface BaseNetService : OMTNetWork <NetServerDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
/// 在执行前处理请求，可在此位置添加自定义header
/// @param request request
- (void)handleRequestBeforeExecute:(NSMutableURLRequest * _Null_unspecified)request;
/// 在执行前处理参数，可在此添加通用的入参
/// @param param param
- (void)handleParamBeforeExecute:(NSMutableDictionary * _Null_unspecified)param;
/// 获取防篡改串
/// @param param 请求的全体参数
/// @return 获取防篡改串
- (NSString * _Null_unspecified)getCheckString:(NSMutableDictionary * _Null_unspecified)param SWIFT_WARN_UNUSED_RESULT;
/// 校验响应状态码是否需需要处理的
/// @param statusCode 响应状态码
/// @return 是否需要校验
- (BOOL)isValidateResponseStatusCode:(NSInteger)statusCode SWIFT_WARN_UNUSED_RESULT;
/// 校验逻辑
/// @param statusCode 响应状态码
- (void)handleResponseStatusCode:(NSInteger)statusCode;
/// 处理响应的后解析成模型的消息code值
/// @param model 模型
- (void)handleResponseModel:(ResponseModel * _Null_unspecified)model;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC17CulturalCloudBase18BaseViewController")
@interface BaseViewController : UIViewController
- (void)viewDidLoad;
/// 返回
- (void)back;
/// 点击标题
- (void)onDidTouchTitle;
/// 重新加载action
- (void)loadReapplication;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@property (nonatomic, readonly) BOOL shouldAutorotate;
- (void)closeKeyBoard;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17CulturalCloudBase17CheckStationModel")
@interface CheckStationModel : NSObject
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger districtId;
@property (nonatomic, copy) NSDictionary * _Nullable district;
@property (nonatomic, copy) NSString * _Nonnull group;
@property (nonatomic) NSInteger parentId;
@property (nonatomic) NSInteger parent;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull typeName;
@property (nonatomic) NSInteger level;
@property (nonatomic, copy) NSString * _Nonnull organizationCode;
@property (nonatomic, copy) NSString * _Nonnull industryCode;
@property (nonatomic, copy) NSString * _Nonnull tel;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic, copy) NSString * _Nonnull registeredType;
@property (nonatomic, copy) NSString * _Nonnull membership;
@property (nonatomic, copy) NSString * _Nonnull logo;
@property (nonatomic) NSInteger createdAt;
@property (nonatomic) NSInteger children;
@property (nonatomic) NSInteger grade;
@property (nonatomic) BOOL isDelete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17CulturalCloudBase12CloudService")
@interface CloudService : BaseNetService
@end


SWIFT_CLASS("_TtC17CulturalCloudBase10MobService")
@interface MobService : BaseNetService
@end


SWIFT_CLASS("_TtC17CulturalCloudBase15ModalWindowView")
@interface ModalWindowView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17CulturalCloudBase20UserAuthErrorService")
@interface UserAuthErrorService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class UserProFileModel;

SWIFT_CLASS("_TtC17CulturalCloudBase8UserInfo")
@interface UserInfo : NSObject
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull userid;
@property (nonatomic) NSInteger createdTime;
@property (nonatomic, copy) NSString * _Nonnull realName;
@property (nonatomic) NSInteger roleId;
@property (nonatomic) NSInteger districtId;
@property (nonatomic, copy) NSString * _Nonnull mobile;
@property (nonatomic) NSInteger loginTimes;
@property (nonatomic, copy) NSString * _Nonnull sex;
@property (nonatomic, copy) NSString * _Nonnull createdIp;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull auth;
@property (nonatomic, copy) NSString * _Nonnull avatar;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull salt;
@property (nonatomic) BOOL isLocked;
@property (nonatomic, copy) NSDictionary * _Nullable district;
@property (nonatomic) NSInteger lastLoginTime;
@property (nonatomic, copy) NSString * _Nonnull lastLoginIp;
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, copy) NSString * _Nonnull plaintextPwd;
@property (nonatomic) NSInteger organizationId;
@property (nonatomic) NSInteger districtLevel;
@property (nonatomic, copy) NSArray * _Nullable tags;
@property (nonatomic, copy) NSArray * _Nullable permissions;
@property (nonatomic, strong) UserProFileModel * _Nullable profile;
@property (nonatomic, strong) CheckStationModel * _Nullable organization;
- (void)onModelConvertFinished;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17CulturalCloudBase16UserProFileModel")
@interface UserProFileModel : NSObject
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger userId;
@property (nonatomic, copy) NSString * _Nonnull gender;
@property (nonatomic, copy) NSString * _Nonnull birthday;
@property (nonatomic, copy) NSString * _Nonnull qq;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull idcard;
@property (nonatomic, copy) NSString * _Nonnull types;
@property (nonatomic, copy) NSString * _Nonnull nation;
@property (nonatomic, copy) NSString * _Nonnull district;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic, copy) NSString * _Nonnull education;
@property (nonatomic) BOOL hasDegree;
@property (nonatomic, copy) NSString * _Nonnull degreeName;
@property (nonatomic, copy) NSString * _Nonnull position;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17CulturalCloudBase11UserService")
@interface UserService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
